<a href="https://colab.research.google.com/github/creativmind/python/blob/master/Arrayconcepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ARRAY CONSTRUCTION- 2D**

In [ ]:
import numpy as np

row = int(input("enter row size: "))
col = int(input("enter col size: "))
array = np.ndarray(shape = (row,col),dtype=int)
print("Array size: ",array.size)
print("Array shape: ",array.shape)
print("Array dimension: ",array.ndim)

print("enter %d elements for %dx%d matrix :" %(array.size,row,col))
for i in range(row):
 
  for j in range(col):
    array[i][j]=int(input())
  print("%d row over" %i)

print(array)


    

**ARRAY CONSTRUCTION- MULTI DIMENSIONAL**

In [ ]:
row = int(input("enter row size: "))
col = int(input("enter col size: "))

mdim = int(input("multi demension size: "))
array = np.ndarray(shape = (mdim,row,col),dtype=int)
print("Array size: ",array.size)
print("Array shape: ",array.shape)
print("Array dimension: ",array.ndim)

print("enter %d elements for %dx%dx%d matrix :" %(array.size,mdim,row,col))
for index in range(mdim):

 for i in range(row):
  for j in range(col):
    array[index][i][j]=int(input())
  print("%d - index %d-row over" %(index,i))

print(array)

enter row size: 2
enter col size: 2
multi demension size: 2
Array size:  8
Array shape:  (2, 2, 2)
Array dimension:  3
enter 8 elements for 2x2x2 matrix :
1
2
0 - index 0-row over
3
4
0 - index 1-row over
5
6
1 - index 0-row over
7
8
1 - index 1-row over
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
row = int(input("enter row size: "))
col = int(input("enter col size: "))

mdim = int(input("multi demension size: "))
array = np.ndarray(shape = (mdim,row,col),dtype=int)
print("Array size: ",array.size)
print("Array shape: ",array.shape)
print("Array dimension: ",array.ndim)

val =1
print("%d elements for %dx%dx%d matrix :" %(array.size,mdim,row,col))
for index in range(mdim):

 for i in range(row):
  for j in range(col):
    array[index][i][j]=val
    val = val+1
   
  

print(array)

enter row size: 2
enter col size: 3
multi demension size: 2
Array size:  12
Array shape:  (2, 2, 3)
Array dimension:  3
12 elements for 2x2x3 matrix :
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


**ARRAY RESHAPING**

2X2X3 = 12 = 3X2X2 =2X2X3 = 1X6X2

In [ ]:
reshp1= array.reshape(3,2,2)

reshp2= array.reshape(1,6,2)
print("reshape1")
reshp1


reshape1


array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
print("reshape2")
reshp2

reshape2


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]]])

**APPEND FUNCTION**

In [ ]:
a = np.array(np.arange(0,20)).reshape(4,5)

NameError: ignored

In [ ]:
import numpy as np
a = np.array(np.arange(0,20)).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
import numpy as np
b = np.array(np.arange(0,10)).reshape(2,5)*2
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

**APPEND row wise**

both array should have equal columns  only then rowise append or vertical stacking is possible

In [ ]:
rowwiseappend = np.append(a,b,axis = 0)
rowwiseappend

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

**VERTICAL STACKING**

In [ ]:
VS = np.vstack((a,b))
VS

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

**HORIZONTAL STACKING**

m x n = m  x n

*both array should have equalrows only then colwise append or horizontal stacking is possible*

In [ ]:
import numpy as np
c = np.array(np.arange(0,20)).reshape(4,5)*2
c

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
hs = np.hstack((a,c))
hs

array([[ 0,  1,  2,  3,  4,  0,  2,  4,  6,  8],
       [ 5,  6,  7,  8,  9, 10, 12, 14, 16, 18],
       [10, 11, 12, 13, 14, 20, 22, 24, 26, 28],
       [15, 16, 17, 18, 19, 30, 32, 34, 36, 38]])

**APPEND COL WISE**

In [ ]:
appendcolwise = np.append(a,c,axis=1)
appendcolwise

array([[ 0,  1,  2,  3,  4,  0,  2,  4,  6,  8],
       [ 5,  6,  7,  8,  9, 10, 12, 14, 16, 18],
       [10, 11, 12, 13, 14, 20, 22, 24, 26, 28],
       [15, 16, 17, 18, 19, 30, 32, 34, 36, 38]])

**DELETE OPERATION**

In [ ]:
d = np.delete(hs,1,axis=0)
d

array([[ 0,  1,  2,  3,  4,  0,  2,  4,  6,  8],
       [10, 11, 12, 13, 14, 20, 22, 24, 26, 28],
       [15, 16, 17, 18, 19, 30, 32, 34, 36, 38]])

In [ ]:
d = np.delete(hs,1,axis=1,)
d

array([[ 0,  2,  3,  4,  0,  2,  4,  6,  8],
       [ 5,  7,  8,  9, 10, 12, 14, 16, 18],
       [10, 12, 13, 14, 20, 22, 24, 26, 28],
       [15, 17, 18, 19, 30, 32, 34, 36, 38]])

In [ ]:
d[-1,-1]




38

In [ ]:
greater_than_10 = np.where(d>10,d,0)
greater_than_10

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 12, 14, 16, 18],
       [ 0, 12, 13, 14, 20, 22, 24, 26, 28],
       [15, 17, 18, 19, 30, 32, 34, 36, 38]])

In [ ]:
d[greater_than_10]

array([12, 14, 16, 18, 12, 13, 14, 20, 22, 24, 26, 28, 15, 17, 18, 19, 30,
       32, 34, 36, 38])

https://www.oreilly.com/library/view/python-for-data/9781449323592/ch04.html

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
c=a[a>9]

**INITIALISING AN EMPTY ARRAY**

In [ ]:
empty = np.empty((3,3))